# Use an official Node runtime as the base image
FROM node:latest

# Set the working directory in the container to /app
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install

COPY ./src /src
COPY ./public /public


# Make port 3000 available to the world outside this container
EXPOSE 3000


# Start the app
CMD ["npm", "start"]
