version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5001:5000"
    env_file:
      - ./myapp/.env
    environment:
      - FRONTEND_URL=http://localhost:3001
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5001
