version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    env_file:
      - ./myapp/.env
    environment:
      - VARIABLE_NAME=actual_value
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_VARIABLE_NAME=actual_value
