name: Python/React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f myapp/requirements.txt ]; then pip install -r myapp/requirements.txt; fi
    - name: Build
      env: 
        BACKENV: ${{ secrets.BACKENV }}
        FIREBASEADMINSDK: ${{ secrets.FIREBASEADMINSDK }}
      run: |
        echo "$FIREBASEADMINSDK" > ./myapp/paxxium-firebase-adminsdk-2l9cl-3bb25d079e.json
        echo "$BACKENV" > ./myapp/.env
        python run.py
    - name: Run tests
      run: pytest

  build-react:
    needs: build-python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Build
      env: 
        FRONTENV: ${{ secrets.FRONTENV }}
      run: |
        echo "$FRONTENV" > ./.env
        npm start
